# Air
[air]
app_name = "goproxy-china"
debug_mode = true
address = "localhost:8080"
minifier_enabled = true
gzip_enabled = true

# Zerolog
[zerolog]
logger_level = "debug"

# Qiniu
[qiniu]
access_key = "<ACCESS_KEY>"
secret_key = "<SECRET_KEY>"
bucket_name = "<BUCKET_NAME>"
bucket_endpoint = "<BUCKET_ENDPOINT>"

# Goproxy
[goproxy]
go_bin_name = "go"
max_go_bin_workers = 8
supported_sumdb_hosts = ["sum.golang.org"]
