# Air
[air]
app_name = "goproxy-china"
debug_mode = true
address = "localhost:8080"
minifier_enabled = true
gzip_enabled = true
coffer_enabled = true
i18n_enabled = true

# Zerolog
[zerolog]
logger_level = "debug"

# Qiniu
[qiniu]
access_key = "<ACCESS_KEY>"
secret_key = "<SECRET_KEY>"
storage_bucket = "<STORAGE_BUCKET>"
storage_bucket_access_endpoint = "<STORAGE_BUCKET_ACCESS_ENDPOINT>"

# Goproxy
[goproxy]
go_bin_name = "go"
max_go_bin_workers = 8
supported_sumdb_hosts = ["sum.golang.org"]
